version: '3.8'

services:
  techshop-service:
    build: .
    container_name: techshop-service
    hostname: techshop-service
    restart: always
    environment:
      - Redis:ConnectionString=redis
    ports:
      - "8002:8080"
    depends_on:
      - redis
    networks:
      - local-net
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-net
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    volumes:
      - type: volume
        source: redis-data
        target: /db
    depends_on:
      - redis
    networks:
      - local-net

volumes:
  redis-data:
    name: redis-data
    driver: local

networks:
  local-net:
    name: local-net
    driver: bridge